[build-system]
requires = ["setuptools>=42", "wheel", "cmake>=3.14"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
# Skip Python 2.7 and PyPy
#skip = ["cp27-*", "pp*", "cp35-*", "cp36-*", "cp37-*", "cp38-", "cp39-*", "cp310-*"]
skip = ["cp27-*", "pp*", "cp35-*", "cp36-*", "cp37-*", "cp38-", "cp39-*", "cp310-*", "cp311-*", "cp312-*"]
# Build for these Python versions
#build = ["cp37-*", "cp38-*", "cp39-*", "cp310-*", "cp311-*", "cp312-*", "cp313-*"]
#build = ["cp311-*", "cp312-*", "cp313-*"]
build = ["cp313-*"]
# Set environment variables
environment = { CMAKE_BUILD_PARALLEL_LEVEL = "4" }
