[build-system]
requires = ["setuptools>=42", "wheel", "cmake>=3.14"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
# Skip Python 2.7 and PyPy
skip = ["cp27-*", "pp*", "cp35-*", "cp36-*"]
# Build for these Python versions
build = ["cp37-*", "cp38-*", "cp39-*", "cp310-*", "cp311-*", "cp312-*", "cp313-*"]
# Set environment variables
environment = { CMAKE_BUILD_PARALLEL_LEVEL = "4" }
