#ifndef OINEUS_GRID_DOMAIN_H
#define OINEUS_GRID_DOMAIN_H

#include <array>
#include <vector>
#include <numeric>
#include <algorithm>
#include <cassert>
#include <stdexcept>
#include <functional>

namespace std {
    template<typename T>
    std::ostream& operator<<(std::ostream& os, const std::vector<T>& v)
    {
        os << "[";

        for(size_t i = 0 ; i < v.size() ; ++i) {
            os << v[i];
            if (i + 1 < v.size())
                os << ", ";
        }

        os << "]";
        return os;
    }

    template<typename Int, size_t D>
    std::ostream& operator<<(std::ostream& os, const std::array<Int, D>& p)
    {
        os << "(";

        for(size_t i = 0 ; i < D ; ++i) {
            os << p[i];
            if (i + 1 < D)
                os << ", ";
        }

        os << ")";
        return os;
    }
}

namespace oineus {

// this function is auto-generated by scripts/freudenthal_cube.py
template<typename Int, size_t D>
constexpr inline std::vector<std::vector<std::vector<Int>>> fr_displacements(size_t dim)
{
    size_t cube_dim = D;

    switch(cube_dim) {
    case 1 :
        switch(dim) {
        case 0 :
            return {
                    {{0}}};
            break;
        case 1 :
            return {
                    {{0}, {1}}};
            break;
        }
        break;
    case 2 :
        switch(dim) {
        case 0 :
            return {
                    {{0, 0}}};
            break;
        case 1 :
            return {
                    {{0, 0}, {0, 1}},
                    {{0, 0}, {1, 1}},
                    {{0, 0}, {1, 0}}};
            break;
        case 2 :
            return {
                    {{0, 0}, {1, 0}, {1, 1}},
                    {{0, 0}, {0, 1}, {1, 1}}};
            break;
        }
        break;
    case 3 :
        switch(dim) {
        case 0 :
            return {
                    {{0, 0, 0}}};
            break;
        case 1 :
            return {
                    {{0, 0, 0}, {0, 1, 0}},
                    {{0, 0, 0}, {1, 1, 0}},
                    {{0, 0, 0}, {0, 1, 1}},
                    {{0, 0, 0}, {1, 1, 1}},
                    {{0, 0, 0}, {0, 0, 1}},
                    {{0, 0, 0}, {1, 0, 0}},
                    {{0, 0, 0}, {1, 0, 1}}};
            break;
        case 2 :
            return {
                    {{0, 0, 0}, {0, 0, 1}, {0, 1, 1}},
                    {{0, 0, 0}, {0, 0, 1}, {1, 0, 1}},
                    {{0, 0, 0}, {1, 0, 0}, {1, 0, 1}},
                    {{0, 0, 0}, {1, 0, 0}, {1, 1, 1}},
                    {{0, 0, 0}, {0, 1, 0}, {1, 1, 0}},
                    {{0, 0, 0}, {1, 0, 1}, {1, 1, 1}},
                    {{0, 0, 0}, {0, 1, 1}, {1, 1, 1}},
                    {{0, 0, 0}, {0, 1, 0}, {0, 1, 1}},
                    {{0, 0, 0}, {0, 0, 1}, {1, 1, 1}},
                    {{0, 0, 0}, {1, 0, 0}, {1, 1, 0}},
                    {{0, 0, 0}, {0, 1, 0}, {1, 1, 1}},
                    {{0, 0, 0}, {1, 1, 0}, {1, 1, 1}}};
            break;
        case 3 :
            return {
                    {{0, 0, 0}, {0, 0, 1}, {0, 1, 1}, {1, 1, 1}},
                    {{0, 0, 0}, {1, 0, 0}, {1, 0, 1}, {1, 1, 1}},
                    {{0, 0, 0}, {0, 1, 0}, {1, 1, 0}, {1, 1, 1}},
                    {{0, 0, 0}, {0, 0, 1}, {1, 0, 1}, {1, 1, 1}},
                    {{0, 0, 0}, {1, 0, 0}, {1, 1, 0}, {1, 1, 1}},
                    {{0, 0, 0}, {0, 1, 0}, {0, 1, 1}, {1, 1, 1}}};
            break;
        }
        break;
    }

    throw std::runtime_error("Unknown dimensions");
}


template<typename Int, std::size_t D>
std::array<Int, D>& operator+=(std::array<Int, D>& lhs, const std::array<Int, D>& rhs) {
    for (std::size_t i = 0; i < D; ++i) {
        lhs[i] += rhs[i];
    }
    return lhs;
}

template<typename Int_, size_t D>
class GridDomain {
public:
    using Int = Int_;
    using GridPoint = std::array<Int, D>;
    using GridPointVec = std::vector<GridPoint>;
    using GridPointVecVec = std::vector<GridPointVec>;

    static constexpr std::size_t dim {D};

    static GridPoint origin() {
        GridPoint result;
        result.fill(0);
        return result;
    }

    GridDomain() = default;
    GridDomain(const GridDomain&) = default;
    GridDomain(GridDomain&&) noexcept = default;
    GridDomain& operator=(const GridDomain&) = default;
    GridDomain& operator=(GridDomain&&) noexcept = default;

    GridDomain(const GridPoint& _dims, bool _wrap)
            :dims_(_dims), c_order_(true), wrap_(_wrap)
    {
        if (dims_.size() != dim)
            throw std::runtime_error("Dims size must be equal D");

        if (wrap_ and std::any_of(dims_.begin(), dims_.end(), [](Int x) { return x < 3; }))
            throw std::runtime_error("Must have at least 3 cells in each dimension for wrap=true");

        if (not std::all_of(dims_.begin(), dims_.end(), [](Int x) { return x > 0; }))
            throw std::runtime_error("Dims must be positive");

        if (c_order_) {
            strides_[D - 1] = 1;

            for(int d = static_cast<int>(D) - 2 ; d >= 0 ; --d)
                strides_[d] = dims_[d + 1] * strides_[d + 1];
        } else
            throw std::runtime_error("Fortran order not implemented");
    }

    Int size() const
    {
        return std::accumulate(dims_.cbegin(), dims_.cend(), Int(1), std::multiplies<Int>());
    }

    Int point_to_id(const GridPoint& v) const
    {
        assert(c_order_);
        return std::inner_product(v.begin(), v.end(), strides_.begin(), 0);
    }

    GridPoint id_to_point(Int i) const
    {
        GridPoint result;

        assert(0 <= i and i < size());

        if (c_order_)
            for(size_t d = 0 ; d < dim ; ++d) {
                result[d] = i / strides_[d];
                i = i % strides_[d];
            }
        else
            throw std::runtime_error("Fortran order not supported");
        return result;
    }

    GridPoint wrap_point(const GridPoint& v) const
    {
        assert(wrap_);
        GridPoint result = v;
        for(size_t i = 0 ; i < dim ; ++i)
            result[i] %= dims_[i];
        return result;
    }

    bool contains(const GridPoint& v) const
    {
        for(size_t i = 0 ; i < dim ; ++i)
            if (v[i] >= dims_[i] or v[i] < 0)
                return false;
        return true;
    }

    template<class Cont>
    static GridPoint add_points(const GridPoint& x, const Cont& y)
    {
        assert(x.size() == y.size());

        GridPoint z = x;
        for(size_t i = 0 ; i < dim ; ++i)
            z[i] += y[i];

        return z;
    }

    // helper function to get Freudenthal displacements
    GridPointVecVec get_fr_displacements(size_t d) const
    {
        GridPointVecVec result;

        for(auto&& disps: fr_displacements<Int, D>(d)) {
            result.emplace_back();
            for(auto&& disp: disps) {
                GridPoint p;
                assert(disp.size() == p.size());
                for(size_t k = 0 ; k < disp.size() ; ++k)
                    p[k] = disp[k];
                result.back().push_back(p);
            }
        }

        return result;
    }

    Int get_n_cubes_in_dimension(dim_type d) const
    {
        if (d > D)
            throw std::runtime_error("bad dimension argument to get_n_cubes_in_dimension");

        // we have domain_dim directions,
        // a d-dimensional face is a subset of cardinality d
        // return domain_dim \choose d

        Int result = 1;

        for(Int k = D; k > (Int)(D - d); --k)
            result *= k;

        for(Int k = 1; k <= (Int)d; ++k)
            result /= k;

        return result;
    }

    GridPoint shape() const { return dims_; }
    bool wrap() const { return wrap_; }

    template<typename I, size_t DD>
    friend std::ostream& operator<<(std::ostream& out, const GridDomain<I, DD>& g);

    bool operator==(const GridDomain& other) const { return dims_ == other.dims_ && wrap_ == other.wrap_; }
    bool operator!=(const GridDomain& other) const { return !(*this == other); }

private:
    GridPoint dims_;
    GridPoint strides_;
    bool c_order_ {true};
    bool wrap_ {false};
};

template<typename Int, size_t D>
std::ostream& operator<<(std::ostream& out, const GridDomain<Int, D>& g)
{
    out << "Domain(dims=" << g.dims_ << ", strides = " << g.strides_ << ", c_order = " << g.c_order_ << ", wrap = " << g.wrap_ << ")";
    return out;
}

} // namespace oineus

// Hash specialization for GridDomain
namespace std {
    template<typename Int, size_t D>
    struct hash<oineus::GridDomain<Int, D>> {
        size_t operator()(const oineus::GridDomain<Int, D>& domain) const {
            size_t seed = 0;

            // Hash the shape/dims
            auto shape = domain.shape();
            for (size_t i = 0; i < D; ++i) {
                // Combine hash using the same technique as boost::hash_combine
                seed ^= std::hash<Int>{}(shape[i]) + 0x9e3779b9 + (seed << 6) + (seed >> 2);
            }

            // Hash the wrap flag
            seed ^= std::hash<bool>{}(domain.wrap()) + 0x9e3779b9 + (seed << 6) + (seed >> 2);

            return seed;
        }
    };
}

#endif //OINEUS_GRID_DOMAIN_H